#!/usr/bin/env tsx
/**
 * Pre-fetch a curated set of MingCute SVGs and bake them into
 * lib/mingcute-icons.ts as a `Record<name, svgString>` constant.
 *
 * Run when the icon set used by DESIGN.md / preview prompts changes:
 *   pnpm tsx scripts/build-icon-manifest.ts
 *
 * The generated module has zero runtime dependencies. generate-previews.ts
 * imports it and replaces <i data-mc="name" data-size="16"></i> placeholders
 * inside the LLM-produced HTML.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const REPO = 'Richard9394/MingCute';
const REF = 'main';
const FLAT_INDEX = `https://data.jsdelivr.com/v1/package/gh/${REPO}@${REF}/flat`;
const CDN = `https://cdn.jsdelivr.net/gh/${REPO}@${REF}`;

const ICONS: string[] = [
  'arrow_right_line', 'arrow_right_fill',
  'arrow_left_line', 'arrow_left_fill',
  'down_line', 'up_line',
  'search_line',
  'close_line', 'close_circle_fill',
  'check_line',
  'heart_line', 'heart_fill',
  'star_line', 'star_fill',
  'bookmark_line', 'bookmark_fill',
  'external_link_line',
  'settings_3_line', 'settings_3_fill',
  'user_3_line', 'user_3_fill',
  'home_3_line', 'home_3_fill',
  'folder_line', 'folder_fill',
  'file_line', 'file_fill',
  'message_3_line', 'message_3_fill',
  'notification_line', 'notification_fill',
  'edit_line', 'edit_fill',
  'delete_2_line', 'delete_2_fill',
  'plus_line', 'plus_fill',
  'subtract_line', 'subtract_fill',
  'more_1_line', 'more_1_fill',
  'play_line', 'play_fill',
  'pause_line', 'pause_fill',
  'refresh_3_line', 'refresh_3_fill',
  'light_line', 'light_fill',
  'rocket_line', 'rocket_fill',
];

type Index = { files: { name: string }[] };

async function buildIndex(): Promise<Map<string, string>> {
  const res = await fetch(FLAT_INDEX);
  if (!res.ok) throw new Error(`flat index failed: ${res.status}`);
  const data = (await res.json()) as Index;
  const map = new Map<string, string>();
  for (const f of data.files) {
    const m = f.name.match(/^\/svg\/([a-z0-9_]+)\/([a-z0-9_]+)\.svg$/);
    if (!m) continue;
    map.set(m[2], f.name);
  }
  return map;
}

function normalizeSvg(raw: string): string {
  let s = raw.trim();
  s = s.replace(/\s(width|height)="[^"]*"/g, '');
  s = s.replace(/\sfill="#[0-9A-Fa-f]+"/g, ' fill="currentColor"');
  // MingCute SVGs include a hidden 24x24 boundary <path> (a long string of
  // ".000" subpaths used to lock the viewBox). It has no fill attribute and
  // relies on parent <g fill="none">, but at small icon sizes the browser
  // still rasterizes its outline and produces visible noise on top of the
  // real glyph. Strip every <path> that has no `fill=` attribute.
  s = s.replace(/<path(?![^>]*\sfill=)[^>]*\/>/g, '');
  if (!/viewBox=/.test(s)) s = s.replace('<svg ', '<svg viewBox="0 0 24 24" ');
  if (!/xmlns=/.test(s)) s = s.replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" ');
  return s;
}

async function main(): Promise<void> {
  console.log(`Indexing MingCute @ ${REF}...`);
  const idx = await buildIndex();
  console.log(`Index has ${idx.size} icons.`);

  const out: Record<string, string> = {};
  const missing: string[] = [];
  for (const name of ICONS) {
    const path = idx.get(name);
    if (!path) {
      missing.push(name);
      continue;
    }
    const url = `${CDN}${path}`;
    const r = await fetch(url);
    if (!r.ok) {
      missing.push(name);
      continue;
    }
    out[name] = normalizeSvg(await r.text());
    process.stdout.write('.');
  }
  process.stdout.write('\n');

  if (missing.length) {
    console.warn(`Missing: ${missing.join(', ')}`);
  }

  const dest = join(process.cwd(), 'lib', 'mingcute-icons.ts');
  const body = [
    '// AUTO-GENERATED by scripts/build-icon-manifest.ts',
    '// Source: github.com/Richard9394/MingCute (MIT)',
    '// Run `pnpm tsx scripts/build-icon-manifest.ts` to refresh.',
    '',
    'export const MINGCUTE_ICONS: Record<string, string> = {',
    ...Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
    '};',
    '',
    'export const FALLBACK_SVG = \'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="4" y="4" width="16" height="16" rx="2"/></svg>\';',
    '',
  ].join('\n');
  writeFileSync(dest, body, 'utf8');
  console.log(`Wrote ${dest} — ${Object.keys(out).length} icons.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
